Repository BigFunnyMountain/bookKing, pull requests merged in 2025-04, with the labels that each got.

#4 Feat : basic books' mvp
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/controller/BookController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/AddBookRequestDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/UpdateBookRequestDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/UpdateBookStockRequestDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/response/BookResponseDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/entity/Book.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/mapper/BookMapper.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/repository/BookRepository.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
  src/main/resources/application.yml
Labels: feat

#5 feat(workflow): integration.yml 작성
  .github/workflows/integration.yml
  build.gradle
Labels: feat

#6 chore(swagger): swagger 의존성 추가 및 설정 추가
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/GlobalExceptionHandler.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/SwaggerConfig.java
Labels: chore

#8 Feat/payment
  .gitignore
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/entity/Book.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/RedissonConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/enums/ErrorMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/controller/PaymentController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/resources/redisson.yml
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
Labels: feat

#13 feat: deploy.yml 작성
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  Dockerfile
  build.gradle
  src/main/resources/application-release.yml
Labels: bug, feat, test

#10 Feat/order CRUD
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/controller/OrderController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/dto/OrderResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/entity/Order.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/entity/enums/OrderStatus.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/repository/OrderRepository.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/service/OrderService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/order/OrderServiceTest.java
Labels: feat

#12 Feat/payment
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/RedissonConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/enums/ErrorMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/controller/PaymentController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/dto/PaymentRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/dto/request/PaymentRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/config/SecurityConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/dto/response/UserResponse.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
Labels: bug, feat, test

#14 Feat/review
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/QueryDslConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/controller/OrderController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/entity/Order.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/entity/enums/OrderStatus.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/enums/OrderStatus.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/repository/OrderRepository.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/repository/OrderRepositoryCustom.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/repository/OrderRepositoryCustomImpl.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/service/OrderService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/constant/ReviewConstants.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/controller/ReviewController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/dto/request/ReviewRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/dto/response/ReviewResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/entity/Review.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/enums/ReviewState.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/enums/StarRating.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/repository/ReviewRepository.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/repository/ReviewRepositoryCustomImpl.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/service/ReviewService.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/order/OrderServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/review/ReviewServiceTest.java
Labels: feat, test

#15 feat: slack 알림 설정
  .DS_Store
  .github/workflows/integration.yml
  .gitignore
Labels: feat, refactor

#16 Feat / books
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/controller/BookController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/AddBookRequestDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/SearchBookRequestDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/UpdateBookRequestDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/response/BookDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/response/BookResponseDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/response/SearchBookResponseDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/entity/Book.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/mapper/BookMapper.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/SearchBookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/GlobalExceptionHandler.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/WebClientConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/dto/ErrorResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/enums/ErrorMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/dto/OrderResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/entity/Order.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/service/OrderService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-release.yml
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/order/OrderServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
Labels: bug, chore, feat, test

#17 chore: 설정 파일 수정 및 DS_Store 캐시 삭제
  build.gradle
  gradlew
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/xyz/.DS_Store
  src/main/java/xyz/tomorrowlearncamp/.DS_Store
  src/main/java/xyz/tomorrowlearncamp/bookking/.DS_Store
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/.DS_Store
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/RedissonConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-release.yml
  src/main/resources/application.yml
Labels: chore, test

#18 Feat/user
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/config/ElasticsearchConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/controller/BookSearchController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/dto/BookSearchResponseDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/entity/ElasticBookDocument.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/service/ElasticBookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/entity/RefreshToken.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/aws/AwsS3Config.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/aws/S3Upload.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/controller/UserController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/entity/User.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/controller/UserControllerTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/service/UserServiceTest.java
Labels: test

#20 Feat/elasticsearch
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/config/ElasticsearchConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/controller/BookSearchController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/controller/ElasticBookSearchController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/document/ElasticBookDocument.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/dto/BookSearchResponseDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/dto/ElasticBookSearchResponseDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/service/ElasticBookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/entity/Book.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/entity/BookSource.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/mapper/BookMapper.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-release.yml
  src/main/resources/elastic/book-mapping.json
  src/main/resources/elastic/book-setting.json
  src/main/resources/elastic/stopwords.txt
  src/main/resources/elastic/synonym.txt
  src/main/resources/elastic/user_dictionary.txt
Labels: chore, feat, refactor

#21 Feat/logstash logback-spring.xml 변경
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/controller/BookTestController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/repository/BookRepository.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: feat

#22 fix: dockerfile 수정
  Dockerfile
Labels: bug, chore, infra

#23 chore: logstash 환경변수 변경
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: bug, chore

#24 fix: application.yml 수정
  src/main/resources/application.yml
Labels: bug, chore

#28 fix: datasource config 수정
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/DataSourceConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/RedissonConfig.java
  src/main/resources/application-release.yml
Labels: bug, chore, infra

#35 refactor(security): cors 추가
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/config/SecurityConfig.java
Labels: chore, refactor

#40 Feat/keyword
  build.gradle
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/OpenAIConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/keyword/controller/KeywordController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/keyword/dto/KeywordRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/keyword/dto/KeywordResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/keyword/service/KeywordService.java
  src/main/resources/application-dev.yml
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/keyword/service/KeywordServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/order/OrderServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/review/ReviewServiceTest.java
Labels: chore, docs, feat, test
