Repository BigFunnyMountain/bookKing, pull requests merged in 2025-05, with the labels that each got.

#42 feat : Book TestCode 추가 & 로컬 테스트 환경에 필요한 ELK dockerfile 추가
  Dockerfile.elastic
  Dockerfile.kibana
  Dockerfile.logstash
  docker-compose.local.yml
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/controller/BookController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/AddBookRequestDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/UpdateBookRequestDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/mapper/BookMapper.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/SearchBookService.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/review/ReviewServiceTest.java
Labels: chore

#45 Feat/payment
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/enums/ErrorMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/dto/OrderResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/entity/Order.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/service/OrderService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/controller/PaymentController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/dto/request/PaymentBuyRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/dto/request/PaymentReturnRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/dto/response/PaymentReturnResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/order/OrderServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
Labels: feat, test

#47 refactor: controller 공통 Response 적용
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/controller/BookController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/controller/ElasticBookSearchController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/GlobalExceptionHandler.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/enums/ErrorMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/exception/ForbiddenRequestException.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/keyword/controller/KeywordController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/controller/OrderController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/controller/ReviewController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/entity/Review.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/controller/AuthController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/dto/AuthUser.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/controller/UserController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/service/UserService.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/service/UserServiceTest.java
Labels: refactor

#44 Refactor/user
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/enums/ErrorMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/controller/AuthController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/service/UserService.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/service/UserServiceTest.java
Labels: refactor

#49 refactor: Handler 추가
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/GlobalExceptionHandler.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/enums/ErrorMessage.java
Labels: refactor

#54 feat: 재색인 및 검색 API 추가
  docker-compose.local.yml
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/controller/BookController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/AddBookRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/SearchBookRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/UpdateBookRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/request/UpdateBookStockRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/response/BookResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/response/SearchBookResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/controller/ElasticBookSearchController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/dto/ElasticBookSearchResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/service/ElasticBookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/mapper/BookMapper.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/repository/BookRepository.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/SearchBookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/GlobalExceptionHandler.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/enums/ErrorMessage.java
  src/main/resources/application-dev.yml
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookServiceTest.java
Labels: bug, chore, feat, refactor

#52 feat: /api/v1/paymentV1 추가
  docker-compose.local.yml
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/controller/BookController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/repository/BookRepository.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/controller/PaymentController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/config/SecurityConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/dto/AuthUser.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
Labels: bug, feat, test

#50 Docs/readme
  README.md
  img.png
  img_1.png
  img_2.png
Labels: docs

#57 Refactor/exception
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/dto/response/BookResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/document/ElasticBookDocument.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/entity/ElasticBookDocument.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/service/ElasticBookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/entity/Book.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/repository/BookRepository.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/GlobalExceptionHandler.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/config/WebClientConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/dto/CustomExceptionDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/dto/ErrorResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/dto/Response.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/dto/SuccessResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/dto/ValidationExceptionDto.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/enums/ErrorMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/common/exception/AccessDeniedHandlerImpl.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/dto/OrderResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/entity/Order.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/service/OrderService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/dto/response/ReviewResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/entity/Review.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/repository/ReviewRepositoryCustomImpl.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/keyword/service/KeywordServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/order/OrderServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/review/ReviewServiceTest.java
Labels: feat, refactor

#59 feat: RefreshToken 로 accessToken 자동 재발급 코드 추가
  src/main/java/xyz/tomorrowlearncamp/bookking/common/enums/ErrorMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/common/enums/RedirectionMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/common/jwt/JwtAuthenticationFilter.java
  src/main/java/xyz/tomorrowlearncamp/bookking/config/SecurityConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/entity/Book.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/entity/RefreshToken.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/repository/RefreshTokenRepository.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthService.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthServiceTest.java
Labels: feat

#61 fix: sonarQube issues 해결
  src/main/java/xyz/tomorrowlearncamp/bookking/common/entity/AuthUser.java
  src/main/java/xyz/tomorrowlearncamp/bookking/common/jwt/JwtAuthenticationFilter.java
  src/main/java/xyz/tomorrowlearncamp/bookking/common/jwt/JwtAuthenticationToken.java
  src/main/java/xyz/tomorrowlearncamp/bookking/config/SecurityConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/config/datasource/ElasticsearchConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/service/ElasticBookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/keyword/dto/KeywordRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/keyword/service/KeywordService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/dto/OrderResponse.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/service/OrderService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/review/consts/ReviewConstants.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/dto/SignupRequest.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/entity/User.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/enums/UserRole.java
  src/test/java/xyz/tomorrowlearncamp/bookking/BookKingApplicationTests.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/order/OrderServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/service/UserServiceTest.java
Labels: refactor

#62 fix: UserRole.of() 메서드 수정 및 BookService 필드 수정
  src/main/java/xyz/tomorrowlearncamp/bookking/common/enums/ErrorMessage.java
  src/main/java/xyz/tomorrowlearncamp/bookking/config/SecurityConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/enums/UserRole.java
Labels: bug

#64 fix: security config 수정
  src/main/java/xyz/tomorrowlearncamp/bookking/config/SecurityConfig.java
Labels: bug

#65 refactor: reindex requestParam 및 로직 수정
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/controller/ElasticBookSearchController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
Labels: refactor

#67 test: paymentServiceTest 수정 및 추가
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/entity/Order.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/enums/OrderStatus.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/order/service/OrderService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/service/UserService.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/order/service/OrderServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/service/UserServiceTest.java
Labels: test

#51 hotfix : applying logstash to purchase and search api
  src/main/java/xyz/tomorrowlearncamp/bookking/common/enums/LogType.java
  src/main/java/xyz/tomorrowlearncamp/bookking/common/util/LogUtil.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/controller/ElasticBookSearchController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/service/ElasticBookService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/dto/response/UserResponse.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentServiceTest.java
Labels: bug, test

#69 hotfix: datasource 라우팅이 제대로 되지 않던 버그 및 기타 설정 추가
  src/main/java/xyz/tomorrowlearncamp/bookking/BookKingApplication.java
  src/main/java/xyz/tomorrowlearncamp/bookking/config/datasource/DataSourceConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/service/BookService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-release.yml
Labels: bug

#71 fix: if 조건이 반대로 설정되어 있던 부분 수정
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
Labels: bug

#72 fix: swagger 설정 코드 및 분산락 코드 수정
  src/main/java/xyz/tomorrowlearncamp/bookking/config/SecurityConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/config/SwaggerConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
Labels: bug

#74 Docs/readme
  README.md
  docs/api/auth-api.md
  docs/api/book-api.md
  docs/api/keyword-api.md
  docs/api/order-api.md
  docs/api/payment-api.md
  docs/api/review-api.md
  docs/api/search-api.md
  docs/api/user-api.md
  docs/index.md
  docs/technical/Aurora_Cluster_사용_이유.md
  docs/technical/Bulk_Insert.md
  docs/technical/ES_LowLevel로_구현한_이유.md
  docs/technical/Jenkins를_사용한_이유.md
  docs/technical/OpenAI_API_사용한_이유.md
  docs/troubleshooting/API호출을위한WebClient트러블슈팅.md
  docs/troubleshooting/Elasticsearch자동완성기능V1~3.md
  docs/troubleshooting/동시성제어시레이스컨디션발생해결.md
  docs/troubleshooting/모니터링구축기.md
  docs/troubleshooting/잘되던애플리케이션의HealthCheck가갑자기실패한이유.md
Labels: docs

#81 release v1.1
  src/main/java/xyz/tomorrowlearncamp/bookking/config/SecurityConfig.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/keyword/service/KeywordService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthService.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/user/repository/UserRepository.java
  src/test/java/xyz/tomorrowlearncamp/bookking/domain/user/auth/service/AuthServiceTest.java
Labels: release

#83 Docs/readme2
  README.md
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/controller/ElasticBookSearchController.java
Labels: docs

#84 Release v1.2
  README.md
  docker-compose.yml
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/book/elasticsearch/controller/ElasticBookSearchController.java
  src/main/java/xyz/tomorrowlearncamp/bookking/domain/payment/service/PaymentService.java
Labels: release

#85 docs: 결제 처리 성능 수정
  README.md
Labels: chore, docs

#87 Docs/readme
  README.md
  img.png
  img_1.png
  img_2.png
Labels: chore, docs
